title = 'nshan.is'
baseURL = 'https://nshan651.github.io/'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  # relatedtext = "Related"
  favicon = "/favicon.ico"

  # list items
  datesinlist = true
  authorsinlist = true

  # footer items
  # nextprev = true
  taglist = true
  showrss = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'onedark'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
