events {
    worker_connections 1024;
}

pid /home/nick/git/nshan651.github.io/nginx.pid;

http {
   access_log /home/nick/git/nshan651.github.io/nginx_access.log;
   error_log /home/nick/git/nshan651.github.io/nginx_error.log;

   types {
        text/html html;
        text/css css;
        application/javascript js;
        image/jpeg jpeg jpg;
        image/png png;
        image/gif gif;
        image/x-icon ico;
        image/svg+xml svg;
    }

    server {
        listen 8080;
        server_name localhost;

        root /home/nick/git/nshan651.github.io/public;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
            expires 1d;
            add_header Cache-Control "public";
        }

        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

}

